#!/usr/bin/perl
#Manualstart V2.0 Perl edition! 
use warnings;
use strict;
require '/opt/ifmi/pm-common.pl';
use Term::ANSIScreen qw(cls);
use YAML qw( DumpFile LoadFile );
use Config::Simple;
 
my $conf = &getConfig;
my %conf = %{$conf};
my $conffile = "/opt/ifmi/poolmanager.conf";
#Globals
sub THELINE {
	print "-================================================-\n";
}
my $clear_screen = cls();


my $msconf = new Config::Simple('manualstart2.conf');
my $dasht = $msconf->param('dasht');
my $extradebug = $msconf->param('extradebug');
my $mdebug = $msconf->param('debug');
my $usescreen = $msconf->param('usescreen');
sub readconf {
  my $msconffile = '/opt/pimp/manualstart.conf';
  if (! -e $msconffile) {
    exec('/usr/lib/cgi-bin/config.pl');
  } 
  my $c;
  $c = LoadFile($msconffile);
  return($c);
}
sub startup {
	print $clear_screen;
	&THELINE;
	print "Poolmanager Manual mining starter & profile tester\n";
	&THELINE;
}	

sub optionsmenu {
	&THELINE;
	print "Options\n";
	&THELINE;
	print "Dasht is $dasht\n";
	print "or done to return to the main menu.\n";
	print "Change option #: "; my $coption = <>; print "\n";
	if ($coption == 1 ) {
			if  ($dasht eq "On") {
				my $dasht = "Off";
				print "\nTurning -T Off\n";
				$msconf->param('dasht', 'Off');
			}
			elsif ($dasht eq "Off") {
				print "\nTurning -T on\n";
				$msconf->param('dasht', 'On');
			}
		$msconf->save();
		&optionsmenu;
	}
	elsif ($coption == 2 ) {
		print "\nTurning $coption off";
		&optionsmenu;
	}
	elsif ($coption =~ m/d(one)?/i) {
		&mainmenu;
	}else {
		print "\nInvalid selection. Try again.\n"; &optionsmenu;
	}

}
sub mainmenu {
	&THELINE;
	print "Select an option from the menu below:\n";
	&THELINE;
	print "1. Change options\t 7.Start Heavy\n";
	print "2. scrypt\t  8. X11 (SPH-SGminer)\n";
	print "3. scrypt-n\t 9. X11 (X11mod miner)\n";
	print "4. Keccak(Sha3)\t 10. X13 (X13mod miner)\n";
	print "5. Quark\t 11. Scrypt ChaCha\n";
	print "6. Scrypt-Jane\t 12. Jackpotcoin\n";
	print "q - Quit\n";
	print "My Choice: "; my $choice = <>;
	if ($choice =~ 1) { &optionsmenu;
	}
	elsif ($choice =~ m/q(uit)?/i) {
	print "Exiting....";
	} else {
		print "Invalid selection. Try again.\n"; &mainmenu;
	}
}

sub runminer {
	my $moptions = "-T --debug";
	print "Starting miner with $moptions\n";
	print "Command line syntax saved to /root/manualstart.run for easy reuse.";
}
&startup;
&mainmenu;

