#!/usr/bin/perl
#Manualstart V2.0 Perl edition! 
use warnings;
use strict;
require '/opt/ifmi/pm-common.pl';
use Term::ANSIScreen qw(cls);

my $conf = &getConfig;
my %conf = %{$conf};
my $conffile = "/opt/ifmi/poolmanager.conf";
#Globals
sub theline {
	print "-================================================-\n";
}
my $clear_screen = cls();




sub startup {
	&THELINE;
	print "Poolmanager Manual mining starter & profile tester\n";
	&THELINE;
}	
&startup;

sub mainmenu {
	&THELINE;
	print "Select an option from the menu below:\n";
	&THELINE;
	print "1. Change options\t 7.Start Heavy\n";
	print "2. scrypt\t  8. X11 (SPH-SGminer)\n";
	print "3. scrypt-n\t 9. X11 (X11mod miner)\n";
	print "4. Keccak(Sha3)\t 10. X13 (X13mod miner)\n";
	print "5. Quark\t 11. Scrypt ChaCha\n";
	print "6. Scrypt-Jane\t 12. Jackpotcoin\n";
	print "q - Quit\n";
	my $choice = <>;
	if ($choice =~ 1) { &optionsmenu;
	}
	elsif ($choice =~ m/q(uit)?/i) {
	print "Exiting....";
	} else {
		print "Invalid selection. Try again.\n"; &mainmenu;
	}

}
&mainmenu;