#!/usr/bin/perl
#Manualstart V2.0 Perl edition! 
use warnings;
use strict;
require '/opt/ifmi/pm-common.pl';
my $conf = &getConfig;
my %conf = %{$conf};
my $conffile = "/opt/ifmi/poolmanager.conf";
#Globals
my $THELINE = (print "-================================================-\n");



sub startup {
	$THELINE
	print "Poolmanager Manual mining starter & profile tester\n"
}	
&startup;
my $continue = <>; chomp $continue;
	if ($continue =~ m/y(es)?/i)  {
	print "GOING AHEAD\n";
	&domenu;
} else {
	print "Exiting....";
	}
sub domenu {
print "test\n";
#my @algos = qw(scrypt scryptn keccak x11 qubit heavy groestl jackpot);
#foreach $algo (@algos) {
#	$algo = "\t . $algo";
#	$algo .= "\n";
#	}
}
